DevsKonnekt/DevsKonnekt

.github/workflows/ethicalcheck.yml

This pull request applies OWASP API security checks to identify and address potential security vulnerabilities in the API code. The Open Web Application Security Project (OWASP) provides a set of best practices and guidelines for securing web applications, including APIs.
- Implemented OWASP API security checks to identify and address potential vulnerabilities.
- Applied recommended security measures and mitigations to enhance the security of the API.
Ensuring the security of our API is critical to protect sensitive data, prevent unauthorized access, and maintain the trust of our users. By applying OWASP API security checks, we proactively identify and address potential security vulnerabilities, reducing the risk of security breaches and data leaks.
Please review the changes made in this …

Apply OWASP API security checks and address vulnerabilities if found

---

Backend/.eslintrc.cjs
Backend/.gitignore
Backend/config/db.js
Backend/controllers/users.js
Backend/index.js
Backend/models/models.js
Backend/models/users.js
Backend/package-lock.json
Backend/package.json
Backend/routes/apiRoutes.js
Backend/routes/users.js

- Create user schema
- Create associated controllers and routes
- Tested the routes

Create user schemas and controllers

---

.github/workflows/greetings.yml

Create an automated new contributor greeting service

Create greetings.yml to greet new contributors

---

Backend/controllers/productservices.js
Backend/controllers/users.js
Backend/index.js
Backend/models/productservices.js
Backend/models/users.js
Backend/routes/productservice.js
Backend/routes/users.js

Created product/service schema that users (developers) offer or purchase on our platform. I have also created relationship with other models/schemas

Created productServiceSchemas

---

.github/workflows/eslint.yml

This pull request applies ESLint code style fixes to ensure consistent and maintainable code. ESLint is a powerful tool that identifies and reports on patterns found in JavaScript code, helping to enforce best practices and improve code quality.
- Resolved code style issues reported by ESLint.
- Applied the Airbnb code style configuration.
Maintaining a consistent code style is crucial for readability, maintainability, and collaboration within the codebase. By adhering to the ESLint rules and using the Airbnb code style, we ensure that our code follows industry best practices and reduces potential bugs and inconsistencies.
Please review the changes made in this pull request and ensure they align with the recommended code style guidelines. If you have any questions or concerns, feel free …

Apply ESLint code style changes and request changes if necessary

---

Backend/controllers/auth.js
Backend/index.js
Backend/middlewares/authValidation.js
Backend/middlewares/customError.js
Backend/middlewares/event.js
Backend/models/users.js
Backend/package-lock.json
Backend/package.json
Backend/routes/auth.js
Backend/routes/productservice.js
Backend/utils/mailing.js

Created register method in auth js  controller to register new users with a corresponding /register route in routes/auth.js and an input validation middleware authValidation

implemented user registration feature

---

Backend/controllers/bookmarks.js
Backend/controllers/comments.js
Backend/controllers/posts.js
Backend/index.js
Backend/models/comments.js
Backend/models/posts.js
Backend/routes/bookmarks.js
Backend/routes/comments.js
Backend/routes/posts.js

This pull request adds the functionality to bookmark posts and comments. Users can now bookmark their favorite posts and comments for easy access later. The changes include modifications to the database schemas for posts and comments, as well as the addition of new routes and controllers for managing bookmarks.

Add bookmarks functionality to posts and comments

---

Backend/controllers/vote.js
Backend/routes/vote.js

Design the database schema to store voting data. Consider the necessary fields such as voter ID, target ID (e.g., post or comment ID), vote type (e.g., upvote or down vote), etc.
Implemented an API endpoint to create a new vote.
Implemented an API endpoint to retrieve a single vote by its ID.
Implemented an API endpoint to update an existing vote. Handle incoming requests, validate the data, and update the vote information in the database. Return appropriate success or error responses.
Implemented an API endpoint to delete a vote by its ID.
Implemented an API endpoint to retrieve all votes associated with a specific target (e.g., post or comment).

Voting API routes

---

Backend/models/profiles.js
Backend/models/users.js
Frontend/app/api/webhooks/clerk/route.js
Frontend/middleware.js

This pull request includes changes to refactor the user and profile models. The changes involve removing unnecessary fields and updating the schema definitions.

Refactor user and profile models

---

Backend/controllers/users.js
Frontend/app/api/webhooks/clerk/route.js

This pull request adds a user existence check in the webhook route to prevent duplicate user creation. It also handles user events such as user creation, update, and deletion.

Add user existence check and handle user events in webhook route

---

Frontend/app/api/webhooks/clerk/route.js
Frontend/components/NavBar.jsx

This pull request includes changes to refactor the API route and update the UserButton component. The API route has been refactored to use the `req.body` instead of `req.json()`. Additionally, the UserButton component has been updated to include an `afterSignOutUrl` prop.

Refactor API route and update UserButton component

---

Frontend/app/api/webhooks/clerk/route.js
Frontend/lib/actions/user.actions.js

This pull request adds user actions for creating, updating, and deleting users. It also updates the webhook route to use the new actions.

Add user actions and update webhook route

---

Backend/controllers/users.js
Frontend/app/api/webhooks/clerk/route.js

This pull request updates the user update and delete methods, fixing a typo in the webhook route.

Update user update and delete methods, fix typo in webhook route

---

Backend/controllers/users.js
Frontend/app/api/webhooks/clerk/route.js

This pull request includes the following changes:
- Fix delete user bug in updateUser function
- Refactor getUser function to use findOne instead of findById
- Refactor request body parsing in Clerk webhook route

Fix delete user bug and refactor getUser and Clerk webhook route

---

Frontend/app/api/webhooks/clerk/route.js

This pull request removes the svix header verification code and adds a console.log statement to log the event object. This change improves the code by simplifying it and providing additional debugging information.

Remove svix header verification and add console.log to log event object

---

Backend/models/profiles.js
Frontend/components/NavBar.jsx
Frontend/components/profile/about.jsx
Frontend/components/profile/aside.jsx
Frontend/components/profile/details.jsx
Frontend/components/profile/editProfile.jsx
Frontend/components/profile/header.jsx
Frontend/lib/actions/profile.actions.js

This pull request updates the profiles model and components. It includes changes to the profiles schema, the aside component, the details component, the navbar component, and the header component.

Update profiles model and components

---

Frontend/app/globals.css
Frontend/components/profile/about.jsx
Frontend/components/profile/editProfile.jsx
Frontend/components/ui/toast.jsx

This pull request refactors the CSS styles and updates the default values of the form in the EditProfile component. It also fixes a bug where the interests field was not properly split into an array.

Refactor CSS styles and update form default values

---

Backend/controllers/profile.js
Backend/controllers/skills.js
Backend/index.js
Backend/models/profiles.js
Backend/routes/skills.js
Frontend/components/myUI/modal.jsx
Frontend/components/profile/about.jsx
Frontend/components/profile/addSkills.jsx
Frontend/lib/actions/skills.actions.js
Frontend/package-lock.json
Frontend/package.json

This pull request adds a skills controller and routes to handle CRUD operations for skills. It also includes the necessary changes to the profile page, including the addition of a modal component and the integration of the addSkills component. Additionally, the getSkills function has been refactored to filter skills by name. The skill actions for the frontend have been added, and the profile model has been updated to reference the skills collection using object IDs. The lodash library has also been added and the skill actions and profile model have been updated accordingly.

Add skills controller and routes

---

Backend/controllers/profile.js
Backend/routes/profile.js
Frontend/components/profile/about.jsx
Frontend/components/profile/addSkills.jsx
Frontend/components/profile/details.jsx
Frontend/components/profile/header.jsx
Frontend/components/profile/skill.jsx
Frontend/lib/actions/profile.actions.js

This pull request adds a new function called deleteSkillFromProfile that allows users to delete a skill from their profile. It also updates the profile components to display the skills and provide an option to delete them.

Add deleteSkillFromProfile function and update profile components

---

Backend/controllers/posts.js
Backend/controllers/vote.js
Backend/index.js
Backend/models/votes.js
Backend/routes/vote.js
Frontend/components/myUI/modal.jsx
Frontend/components/posts/createPost.jsx
Frontend/components/posts/postForm.jsx
Frontend/components/profile/about.jsx
Frontend/components/profile/addSkills.jsx
Frontend/components/profile/details.jsx
Frontend/components/profile/header.jsx
Frontend/components/profile/post.jsx
Frontend/components/profile/postAvatar.jsx
Frontend/components/profile/postsList.jsx
Frontend/components/profile/skill.jsx
Frontend/components/ui/tabs.jsx
Frontend/next.config.js

This pull request includes the following changes:
- Refactor post component and update next.config.js
- Add votesRouter to index.js and update imports in vote.js
- Refactor profile component and fix UI styling
- Add loading state to modal and form components
- Add useState hook and loading prop to PostForm component

Refactor post and profile components, add loading state to modal and form components

---

Frontend/components/myUI/modal.jsx
Frontend/components/posts/fileUploader.jsx
Frontend/components/posts/postForm.jsx

This pull request updates the styles of the modal and file uploader components. It improves the responsiveness and layout of the modal component, and adjusts the height and alignment of the file uploader component.

Update modal and file uploader styles

---

Frontend/components/myUI/modal.jsx
Frontend/components/profile/addSkills.jsx

This pull request updates the modal and addSkills components. It includes changes to the DialogFooter and AddSkills components, improving their functionality and appearance.

Update modal and addSkills components

---

Backend/controllers/comments.js
Backend/controllers/posts.js
Backend/models/comments.js
Backend/routes/comments.js
Frontend/app/globals.css
Frontend/app/posts/[...id]/page.jsx
Frontend/app/posts/comments/[...id]/page.jsx
Frontend/components/myUI/responsiveDialog.jsx
Frontend/components/posts/comment.jsx
Frontend/components/posts/commentDetail.jsx
Frontend/components/posts/commentForm.jsx
Frontend/components/posts/commentsList.jsx
Frontend/components/posts/postDetail.jsx
Frontend/components/profile/post.jsx
Frontend/components/ui/drawer.jsx
Frontend/hooks/useMediaQuery.js
Frontend/lib/actions/posts.actions.js
Frontend/package-lock.json
Frontend/package.json

This pull request includes refactoring of the comment creation and retrieval logic. It also fixes the comment form event listener and ensures that the getPost function always returns a response. Additionally, it refactors the Post component and adds the PostDetailPage component. The pull request also adds the CommentsList component and renames the Comment component to CommentForm. The profile and post links in the components are updated as well. Finally, the pull request adds comment and vote functionality to comments, refactors the comment creation logic, and fixes route paths in comments.js.

Refactor comment creation and retrieval

---

Frontend/app/api/webhooks/stripe/route.js
Frontend/middleware.js

This pull request fixes a webhook error and updates the middleware. The changes include:
- Removed the status code 400 from the webhook error response.
- Added a newTicket variable to store the result of the createTicket function.
- Updated the response to return a JSON object with the message "OK" and the newTicket value.
- Updated the response to return a 200 status code using the Response class.
- Added "/events(.*)" and "/posts(.*)" to the list of excluded paths in the authMiddleware.

Fix webhook error and update middleware

---

Frontend/app/api/webhooks/stripe/route.js

This pull request refactors the POST function in the stripe webhook route. The function has been updated to export as an async function. This change ensures better code readability and maintainability.

Refactor POST function in stripe webhook route

---

Frontend/components/community/events/eventsList.jsx
Frontend/components/shared/checkout.jsx
Frontend/components/shared/checkoutButton.jsx
Frontend/lib/actions/tickets.actions.js

This pull request refactors the checkout process and integrates it with user data. It also adds the CreateEvent component to the EventsList and the SignedIn component to eventsList.jsx.

Refactor checkout process and integrate with user data

---

Backend/controllers/events.js
Backend/routes/events.js

Sample response data when a request for data to be exported as csv or excel is requested.
```json
{
"headers": [
{
"header": "No.",
"key": "no"
},
{
"header": "Event Name",
"key": "eventName",
"width": 30
},
{
"header": "Event Date",
"key": "eventDate",
"width": 20
},
{
"header": "Event Time",
"key": "eventTime",
"width": 20
},
{ "header": "Event Location", "key": "eventLocation", "width": 30 },
{ "header": "Tickets Sold", "key": "ticketsSold", "width": 20 },
{ "header": "Revenue", "key": "revenue", "width": 20 }
],
"rows": [
{
"no": 1,
"eventName": "Unlock Your Inner Hustler: The Ultimate Guide to Making Money Through DevsKonnekt",
"eventDate": "2024-03-11T22:00:00.000Z",
"eventTime": "22:00",
"eventLocation": "https://meet.google.com/ret-yrt-uytu",
"ticketsSold": 3,
"revenue": 150
},
{ …
```

generate event organiser dashboard data
